version: '3'
services:
  web:
    build: .
    ports:
      - "8082:8082"
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 